language: node_js
node_js:
  - "8.11"
services:
  - postgresql
env:
  - NODE_ENV=test
cache:
  directories:
    - node_modules
before_install:
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
install:
  - npm install
before_script:
  - psql -c 'CREATE DATABASE seedpress_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - sequelize db:migrate
  - sequelize db:seed:all
script:
  - "npm run test"
  - "npm run lint"
after_script: "npm -i coveralls@3.0.2 && cat ./coverage/lcov.info | coveralls"
